# Generated by Django 5.2.6 on 2025-10-18 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_add_wallet_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
