name: CI Fullstack Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "Phraser18$"
          POSTGRES_DB: vendorlution
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./vendorlution/backend

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: vendorlution
      DB_USER: postgres
      DB_PASSWORD: "Phraser18$"
      DJANGO_SECRET_KEY: test_secret_key
      DJANGO_DEBUG: "True"

    steps:
